<?php
	use PhpOffice\PhpSpreadsheet\Spreadsheet;
	use PhpOffice\PhpSpreadsheet\Style\Alignment;
	use PhpOffice\PhpSpreadsheet\Style\Fill;
	use PhpOffice\PhpSpreadsheet\RichText\RichText;
	use PhpOffice\PhpSpreadsheet\RichText\Run;

	require_once "phpex/vendor/autoload.php";
	// Create a new PhpSpreadsheet object
	$spreadsheet = new Spreadsheet();

	// Get the active worksheet
	$worksheet = $spreadsheet->getActiveSheet();

	// Set the document properties
	$spreadsheet->getProperties()->setTitle("INVALID QUEUE")
	                             ->setCreator("STANBIC BOP CARD SYSTEM")
	                             ->setLastModifiedBy("STANBIC SZ")
	                             ->setDescription("Invalid queue generated by the BopCard Report system")
	                             ->setSubject("MAS_FILE_REF: XXXXXXXXXXX")
	                             ->setKeywords("invalidQueue");


	// Merge cells A1 to E1 and set the fill color to blue
	$worksheet->mergeCells('A1:E1');
	$worksheet->getStyle('A1')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('0252A1');
	$worksheet->getStyle('A1')->getFont()->setSize(30);

	// Set the text alignment to center horizontally
	$worksheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
	$worksheet->getColumnDimension('A')->setWidth(30);
	$worksheet->getColumnDimension('B')->setWidth(30);
	$worksheet->getColumnDimension('C')->setWidth(30);
	$worksheet->getColumnDimension('D')->setWidth(30);
	$worksheet->getColumnDimension('E')->setWidth(30);
	// Create a RichText object for the cell text
	$richText = new RichText();
	$richText->createTextRun('INVALID QUEUE: AS AT ')->getFont()->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE));
	$richText->createTextRun('Part 2')->getFont()->getColor()->setARGB('ED8900');

	//$richText->getStyle()->getFont()->setSize(24);
	//$richText->getFont()->setBold(true);

	// Set the rich text for cell A1
	$worksheet->setCellValue('A1', $richText);

	// Set the properties for cells A2 to A5
	$cellRange = 'A2:A5';
	$worksheet->getStyle($cellRange)->getFont()->setBold(true);
	$worksheet->getStyle($cellRange)->getFont()->setSize(14);
	$worksheet->getStyle($cellRange)->getFont()->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK));
	$worksheet->getStyle($cellRange)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);
	$worksheet->setCellValue('A2', 'MAS_FILE_REF');
	$worksheet->setCellValue('A3', 'ESB_FILE_REF');
	$worksheet->setCellValue('A4', 'ESB_BATCHES');
	$worksheet->setCellValue('A5', 'INVALID_ITEMS');

	// Set the properties for cells B2 to B5
	$cellRange = 'B2:B5';
	$worksheet->getStyle($cellRange)->getFont()->setSize(14);
	$worksheet->getStyle($cellRange)->getFont()->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK));
	$worksheet->getStyle($cellRange)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
	$worksheet->setCellValue('B2', 'MAS_FILE_REF');
	$worksheet->setCellValue('B3', 'ESB_FILE_REF');
	$worksheet->setCellValue('B4', 'ESB_BATCHES');
	$worksheet->setCellValue('B5', 'INVALID_ITEMS');

	// Set the fill color for cells A3:B3 and A5:B5
	$cellRange = 'A3:B3';
	$worksheet->getStyle($cellRange)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
	$worksheet->getStyle($cellRange)->getFill()->getStartColor()->setRGB('B4C6E7');
	$worksheet->getStyle('A5:B5')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
	$worksheet->getStyle('A5:B5')->getFill()->getStartColor()->setRGB('B4C6E7');

	// Merge cells A6 to E6 and leave them blank
	$worksheet->mergeCells('A6:E6');
	$worksheet->setCellValue('A6', '');

	// Set the fill color for cells A7 to E7
	$cellRange = 'A7:E7';
	$worksheet->getStyle($cellRange)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
	$worksheet->getStyle($cellRange)->getFill()->getStartColor()->setRGB('0252A1');

	// Set the text and font for cells A7 to E7
	$cellRange = 'A7:E7';
	$worksheet->getStyle($cellRange)->getFont()->setBold(true);
	$worksheet->getStyle($cellRange)->getFont()->setSize(14);
	$worksheet->getStyle($cellRange)->getFont()->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE));
	$worksheet->getStyle($cellRange)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
	$worksheet->setCellValue('A7', 'SCHEME_CODE');
	$worksheet->setCellValue('B7', 'CIFID');
	$worksheet->setCellValue('C7', 'FIELD_NAME');
	$worksheet->setCellValue('D7', 'ERR_CODE');
	$worksheet->setCellValue('E7', 'ERR_MESSAGE');

	// Add auto filter and sort for cells A7 to E7
	$worksheet->setAutoFilter('A7:E7');
	//$worksheet->sort('A7', 'asc');

	// Left align cells A8 to E8
	$cellRange = 'A8:E8';
	$worksheet->getStyle($cellRange)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);

	// Save the spreadsheet as "file.xlsx" in the "inv-xlsx" folder
	$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xlsx');
	$writer->save('mike.xlsx');
